server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 5093
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pgm-uf6a91t4nh52x7c8129290.pg.rds.aliyuncs.com:1433/data2
    username: zjtroot
    password: '@zjt10086'
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runsMillis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-timeMillis: 300000
      # 该选项用来验证数据库连接的有效性 psql可以用 select '1' as txt 或 select version(), oracle可以用select 1 from dual
      validation-query: select version()
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  redis:
    mode: single # single sentinel
    # 这里的host是用于 redisTemplate
    host: r-uf61oyw6nuzx1wiu0r.redis.rds.aliyuncs.com
    port: 6379
    database: 2
    password: '@zjt10086'
    timeout: 6000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000ms

# 微信支付-炫彩时代-同"尚投票"
vendor:
  wx:
    config:
      app_id: wxf094ddb11027d734
    pay:
      key: 3798aa234533992f34bb413d5bcabb45
      mch_id: 1584644151
    notify:
      host: 'https://bq.zhiyuanpingtai.com'

# 头条开放平台
bytedance:
  app:
    appid: 'tt0b1d7da09427f5a4'
    appsecret: 'da0026895c5d88613a7133012d454d62963fc800'
  pay:
    appid: '800353003522'
    appsecret: 'rx3fn67aji9kwipvpu7n83cdg430i5nsum5tsuzv'
    merchantid: '1900035300'